---
title: "Research Assistant Training"
output: github_document
---

## To Do

* Add details from the last training [set-up](https://happygitwithr.com/workshops.html?mkt_tok=eyJpIjoiT1RVelptVTNZams0T0dZMiIsInQiOiJlR0orVlVpaHZsRlwveWh5QUJPN2U1Q3BcL0pHVHo5RXJ5UkhabFlwVXM4NlEwcHhRTENQZmVxaEEyNnVLSkRFTTdVa0hyNjk4MkFHYUU1Nkt5VXNtRm9heFM3N3dnUFplZ1V5anpRTWdnWDVscE1lOUR6VzBHaGFQOUFhOGd1QkN3In0=#pre-workshop-set-up).
* Figure out use of branches.
  + Permissions?
  + Push/pull issues?
* Decide on organization or repos (data and size limits).
* Create and clone all projects.
* Migrate to R Markdown.
* Update issues for each project.
* Flesh out details for this training conditioned on the above.

## Project-Oriented Workflow

* Using RStudio projects.
* Safe paths (use the `here` package).
* Beware monoliths (file naming, separate scripts like separate functions).
* Naming conventions (slugs).
* Use `output: github_document` in the YAML of R Markdown documents.
* Discuss the use of *branches*.

## Vocabulary

* repo
* clone
* fork
* committ
* pull
* push
* branch (?)
* pull request

## Advanced Topics

* .gitignore (see example)

## Links

* WTF Workshop (repo)
* All the links shared in the workshop
